version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build:
    executor: 'node/default'
    steps:
      - checkout
      - node/install:
          node-version: 14.18.1
          npm-version: 6.14.15
      - run: npm install
      - run: npm run test